### ISSUE TITLE
布局文件的问题

### ISSUE THREAD

**Issue by ghost** [GcsSloop/Gank#14]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.sloop.gank, PID: 7110
                  android.view.InflateException: Binary XML file line #42: Error inflating class ImageView
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                      at com.sloop.adapter.utils.ViewHolder.<init>(ViewHolder.java:26)
                      at com.sloop.adapter.utils.ViewHolder.getInstance(ViewHolder.java:43)
                      at com.sloop.adapter.utils.CommonAdapter.getView(CommonAdapter.java:77)
                      at android.widget.AbsListView.obtainView(AbsListView.java:2344)
                      at android.widget.ListView.makeAndAddView(ListView.java:1864)
                      at android.widget.ListView.fillDown(ListView.java:698)
                      at android.widget.ListView.fillFromTop(ListView.java:759)
                      at android.widget.ListView.layoutChildren(ListView.java:1659)
                      at android.widget.AbsListView.onLayout(AbsListView.java:2148)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:630)
                      at com.sloop.gank.refresh.RefreshLayout.onLayout(RefreshLayout.java:73)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                      at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                      at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1367)
                      at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:849)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                      at android.view.View.layout(View.java:15596)
                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2072)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1829)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                  	at android.view.Choreographer.doCallbacks(Choreographe

**Comment by GcsSloop** [comment]
收到，感谢反馈
