### ISSUE TITLE
闪退问题反馈处

### ISSUE THREAD

**Issue by GcsSloop** [GcsSloop/Gank#3]
之前没做过多机型测试实在是抱歉，如果有崩溃或者闪退问题可到这里反馈，非常感谢。

**Comment by javaljj** [comment]
小米note2闪退

**Comment by javaljj** [comment]
04-21 09:58:01.654 30427-30427/com.sloop.gank D/ColorDrawable: setColor color = 1140850688, ColorDrawable = android.graphics.drawable.ColorDrawable@d1108d5
04-21 09:58:01.803 30427-30427/com.sloop.gank E/PathParser: error in parsing "c0 1.1.9 2 2 2"
04-21 09:58:01.806 30427-30427/com.sloop.gank D/AndroidRuntime: Shutting down VM
04-21 09:58:01.811 30427-30427/com.sloop.gank E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.sloop.gank, PID: 30427
                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sloop.gank/com.sloop.gank.MainActivity}: android.view.InflateException: Binary XML file line #16: Error inflating class android.support.design.widget.NavigationView
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526)
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:169)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                    at android.os.Looper.loop(Looper.java:194)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5549)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
                                                                 Caused by: android.view.InflateException: Binary XML file line #16: Error inflating class android.support.design.widget.NavigationView
                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:637)
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:418)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
                                                                    at com.sloop.gank.MainActivity.onCreate(MainActivity.java:51)
                                                                    at android.app.Activity.performCreate(Activity.java:5975)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526) 
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:169) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                    at android.os.Looper.loop(Looper.java:194) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5549) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
                                                                 Caused by: java.lang.reflect.InvocationTargetException
                                                                    at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:611)
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                    at com.sloop.gank.MainActivity.onCreate(MainActivity.java:51) 
                                                                    at android.app.Activity.performCreate(Activity.java:5975) 
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111) 
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526) 
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:169) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                    at android.os.Looper.loop(Looper.java:194) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5549) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
                                                                 Caused by: android.content.res.Resources$NotFoundException: File res/drawable-anydpi-v21/ic_menu_welfare.xml from drawable resource ID #0x7f020053
                                                                    at android.content.res.Resources.loadDrawableForCookie(Resources.java:2727)
                                                                    at android.content.res.Resources.loadDrawable(Resources.java:2607)
                                                                    at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:393)
                                                                    at android.content.res.Resources.getDrawable(Resources.java:889)
                                                                    at android.content.Context.getDrawable(Context.java:402)
                                                                    at android.support.v4.content.ContextCompatApi21.getDrawable(ContextCompatApi21.java:26)
                                                                    at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:321)
                                                                    at android.support.v7.widget.TintManager.getDrawable(TintManager.java:147)
                                                                    at android.support.v7.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:421)
                                                                    at android.support.design.internal.NavigationMenuPresenter$NavigationMenuAdapter.prepareMenuItems(NavigationMenuPresenter.java:495)
                                                                    at android.support.design.internal.NavigationMenuPresenter$NavigationMenuAdapter.update(NavigationMenuPresenter.java:426)
                                                                    at android.support.design.internal.NavigationMenuPresenter.updateMenuView(NavigationMenuPresenter.java:113)
                                                                    at android.support.design.widget.NavigationView.inflateMenu(NavigationView.java:233)
                                                                    at android.support.design.widget.NavigationView.<init>(NavigationView.java:168)
                                                                    at android.support.design.widget.NavigationView.<init>(NavigationView.java:94)
                                                                    at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:611) 
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                    at com.sloop.gank.MainActivity.onCreate(MainActivity.java:51) 
                                                                    at android.app.Activity.performCreate(Activity.java:5975) 
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111) 
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526) 
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:169) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                    at android.os.Looper.loop(Looper.java:194) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5549) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
                                                                 Caused by: java.lang.NumberFormatException: Invalid float: "1.1.9"
                                                                    at java.lang.StringToReal.invalidReal(StringToReal.java:63)
                                                                    at java.lang.StringToReal.initialParse(StringToReal.java:160)
                                                                    at java.lang.StringToReal.parseFloat(StringToReal.java:323)
                                                                    at java.lang.Float.parseFloat(Float.java:306)
                                                                    at android.util.PathParser

**Comment by GcsSloop** [comment]
收到

**Comment by lhzmrl** [comment]
我也碰到上面那个问题了，手机是三星S5,调了一下，是Vector Assert的问题，AndroidStudio自带的工具有问题，生成的xml在一些设备上无法解析，官方已经修改了这个问题，现在用最新的工具转换SVG替换就可以了。
https://code.google.com/p/android/issues/detail?id=78981

**Comment by GcsSloop** [comment]
收到，谢谢反馈
